# Generated by Django 4.2.6 on 2023-10-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=50)),
                ("major", models.CharField(max_length=50)),
                ("minor", models.CharField(max_length=50)),
                ("start_date", models.DateField(db_comment="Start Education Date")),
                ("end_date", models.DateField(db_comment="Graduation Date")),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=25)),
                ("img_url", models.CharField(max_length=200)),
            ],
        ),
    ]
