# Generated by Django 4.2.6 on 2023-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="degree_type",
            field=models.CharField(
                choices=[
                    ("B.S.", "Bachelor of Science"),
                    ("M.S.", "Master of Science"),
                    ("M.E.", "Master of Engineering"),
                ],
                default="B.S.",
                max_length=30,
            ),
        ),
    ]
