# Generated by Django 4.2.6 on 2023-10-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_education_degree_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="summary",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
