# Generated by Django 4.2.6 on 2023-10-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_education_coursework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="state",
            field=models.CharField(
                choices=[
                    ("Alabama", "AL"),
                    ("Alaska", "AK"),
                    ("Arizona", "AZ"),
                    ("Arkansas", "AR"),
                    ("California", "CA"),
                    ("Wyoming", "WY"),
                    ("Colorado", "CO"),
                    ("Connecticut", "CT"),
                    ("Delaware", "DE"),
                    ("Florida", "FL"),
                    ("Georgia", "GA"),
                    ("Hawaii", "HI"),
                    ("Idaho", "ID"),
                    ("Illinois", "IL"),
                    ("Indiana", "IN"),
                    ("Iowa", "IA"),
                    ("Kansas", "KS"),
                    ("Kentucky", "KY"),
                    ("Louisiana", "LA"),
                    ("Maine", "ME"),
                    ("Maryland", "MD"),
                    ("Massachusetts", "MA"),
                    ("Michigan", "MI"),
                    ("Minnesota", "MN"),
                    ("Mississippi", "MS"),
                    ("Missouri", "MO"),
                    ("Montana", "MT"),
                    ("Nebraska", "NE"),
                    ("Nevada", "NV"),
                    ("New Hampshire", "NH"),
                    ("New Jersey", "NJ"),
                    ("New Mexico", "NM"),
                    ("New York", "NY"),
                    ("North Carolina", "NC"),
                    ("North Dakota", "ND"),
                    ("Ohio", "OH"),
                    ("Oklahoma", "OK"),
                    ("Oregon", "OR"),
                    ("Pennsylvania", "PA"),
                    ("Rhode Island", "RI"),
                    ("South Carolina", "SC"),
                    ("South Dakota", "SD"),
                    ("Tennessee", "TN"),
                    ("Texas", "TX"),
                    ("Utah", "UT"),
                    ("Vermont", "VT"),
                    ("Virginia", "VA"),
                    ("Washington", "WA"),
                    ("West Virginia", "WV"),
                    ("Wisconsin", "WI"),
                ],
                default="VA",
                max_length=20,
            ),
        ),
    ]
