# Generated by Django 4.2.6 on 2023-10-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_education_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=30, unique=True)),
                (
                    "skill_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lang", "Language"),
                            ("pack", "Package"),
                            ("dev", "Development"),
                            ("soft", "Soft"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(db_comment="Graduation Date", default="Present"),
        ),
        migrations.AlterField(
            model_name="education",
            name="minor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Alabama", "AL"),
                    ("Alaska", "AK"),
                    ("Arizona", "AZ"),
                    ("Arkansas", "AR"),
                    ("California", "CA"),
                    ("Wyoming", "WY"),
                    ("Colorado", "CO"),
                    ("Connecticut", "CT"),
                    ("Delaware", "DE"),
                    ("Florida", "FL"),
                    ("Georgia", "GA"),
                    ("Hawaii", "HI"),
                    ("Idaho", "ID"),
                    ("Illinois", "IL"),
                    ("Indiana", "IN"),
                    ("Iowa", "IA"),
                    ("Kansas", "KS"),
                    ("Kentucky", "KY"),
                    ("Louisiana", "LA"),
                    ("Maine", "ME"),
                    ("Maryland", "MD"),
                    ("Massachusetts", "MA"),
                    ("Michigan", "MI"),
                    ("Minnesota", "MN"),
                    ("Mississippi", "MS"),
                    ("Missouri", "MO"),
                    ("Montana", "MT"),
                    ("Nebraska", "NE"),
                    ("Nevada", "NV"),
                    ("New Hampshire", "NH"),
                    ("New Jersey", "NJ"),
                    ("New Mexico", "NM"),
                    ("New York", "NY"),
                    ("North Carolina", "NC"),
                    ("North Dakota", "ND"),
                    ("Ohio", "OH"),
                    ("Oklahoma", "OK"),
                    ("Oregon", "OR"),
                    ("Pennsylvania", "PA"),
                    ("Rhode Island", "RI"),
                    ("South Carolina", "SC"),
                    ("South Dakota", "SD"),
                    ("Tennessee", "TN"),
                    ("Texas", "TX"),
                    ("Utah", "UT"),
                    ("Vermont", "VT"),
                    ("Virginia", "VA"),
                    ("Washington", "WA"),
                    ("West Virginia", "WV"),
                    ("Wisconsin", "WI"),
                ],
                default="VA",
                max_length=20,
                null=True,
            ),
        ),
    ]
