# Generated by Django 4.2.6 on 2023-10-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_experience_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end",
            field=models.DateField(blank=True, db_comment="End Experience", null=True),
        ),
    ]
